services:
  mysql-db:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Hhdh573)&@/dg'
      MYSQL_DATABASE: task_management
      MYSQL_USER: winfulTaylor
      MYSQL_PASSWORD: Aryeequaye
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/task_management
      SPRING_DATASOURCE_USERNAME: winfulTaylor
      SPRING_DATASOURCE_PASSWORD: Aryeequaye
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql-data:



